name: Super-Linter

# Triggerar workflow på alla push till repositoriet
on: push

jobs:
  super-lint:
    name: Lint kodbasen
    # Kör jobbet på en virtuell Ubuntu-maskin
    runs-on: ubuntu-latest
    
    steps:
      - name: Hämta koden
        uses: actions/checkout@v4
        # Hämtar koden från GitHub repositoryt

      - name: Kör Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Kör Super-Linter för att granska koden
        # Använder GitHub token för att hantera tillåtelser


