name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Förbereda arbetsmiljön
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Hämta koden
        uses: actions/checkout@v4

      - name: Generera Cache Nyckel
        id: cache-key
        run: echo "::set-output name=key::$(echo ${{ runner.os }}-node-${{ matrix.node-version }}-$(hashFiles('**/package-lock.json')))"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: ${{ runner.os }}-node-

  lint-and-test:
    name: Lint och Test
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Skicka startnotifiering till Discord
        uses: DiscordWebhooks/DiscordWebhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'Startar lint och test för push till main eller pull request.'

      - name: Använd Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installera beroenden
        run: npm install

      - name: Kör Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Kör enhetstester
        run: npm test

      - name: Kör CodeQL
        uses: github/codeql-action/analyze@v1

  notify-and-finalize:
    name: Notifiering och Finalisering
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Skicka e-post notifiering om fel
        if: ${{ needs.lint-and-test.result == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Super-Linter - Fel påträffade"
          body: "Linting eller testning misslyckades. Se rapporten för detaljer."
          to: ${{ secrets.EMAIL_ADDRESS }}
          from: GitHub Actions <noreply@github.com>

      - name: Skicka Discord notifiering om resultat
        uses: DiscordWebhooks/DiscordWebhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: ${{ needs.lint-and-test.result == 'failure' && "Linting eller testning misslyckades. Se rapporten för detaljer." || "Allt gick bra. Ingen linter eller testningsfel hittades!" }}

      - name: Auto-korrigera och Commit om framgång
        if: ${{ needs.lint-and-test.result == 'success' }}
        run: |
          npm run lint-fix
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Automatiska linter-fixar" --allow-empty
          git push

