name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Förbereda arbetsmiljön
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Hämta koden
        uses: actions/checkout@v4

      - name: Generera Cache Nyckel
        id: cache-key
        run: echo "::set-output name=key::$(echo ${{ runner.os }}-node-${{ matrix.node-version }}-$(hashFiles('**/package-lock.json')))"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: ${{ runner.os }}-node-

  lint-and-test:
    name: Lint och Test
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Använd Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installera beroenden
        run: npm install

      - name: Kör Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Kör enhetstester
        run: npm test

      - name: Kör CodeQL
        uses: github/codeql-action/analyze@v1

  notify-and-finalize:
    name: Notifiering och Finalisering
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Skicka notifiering
        if: ${{ needs.lint-and-test.result == 'failure' }}
        uses: some/notification-action@v1
        with:
          message: "Linting eller testning misslyckades, se rapporten för detaljer."
          token: ${{ secrets.SLACK_TOKEN }}

      - name: Auto-korrigera och Commit
        if: ${{ needs.lint-and-test.result == 'success' }}
        run: |
          npm run lint-fix
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Automatiska linter-fixar" --allow-empty
          git push








